export enum Products {
  'JSON'
  , 'Tour'
  , 'Nom du produit'
  , 'Référence'
  , 'Prix'
  , 'R&D'
  , 'Production'
  , 'Prod° par instal'
  , 'Installation'
  , 'Actif'
  , 'Qualité'
  , 'Indice technique'
  , 'Image prix'
  , 'Marge brute'
  , 'Taux de marge'
  , 'Demande'
  , 'Stock'
  , 'Prix de MP'
  , 'Notoriété'
  , 'Indice R&D'
  , 'Brevet'
  , 'Nbr de produit vendu'
  , 'Frais de transport'
}